fbc -w all 1.bas
fbc -w all analyse.bas
fbc -w all button.bas
fbc -w all io_input.bas
fbc -w all pwm_cap.bas
fbc -w all sos.bas
fbc -w all stepper.bas
fbc -w all pwm_adc.bas
fbc -w all oszi.bas
fbc -w all rb_oszi.bas
fbc -w all triggers.bas
