# header file auto generated by fb-doc and plugin py_ctypes.bas
# to be inported by libpruio.py (do not change)
from ctypesloader import *
from libprussdrv import tpruss_intc_initdata
_libs = {}
_libs['pruio'] = load_library('pruio')

# pruio_pins.bi: 19
try: P8_03 = 0x06
except: pass

# pruio_pins.bi: 21
try: P8_04 = 0x07
except: pass

# pruio_pins.bi: 23
try: P8_05 = 0x02
except: pass

# pruio_pins.bi: 25
try: P8_06 = 0x03
except: pass

# pruio_pins.bi: 27
try: P8_07 = 0x24
except: pass

# pruio_pins.bi: 29
try: P8_08 = 0x25 
except: pass

# pruio_pins.bi: 31
try: P8_09 = 0x27 
except: pass

# pruio_pins.bi: 33
try: P8_10 = 0x26 
except: pass

# pruio_pins.bi: 35
try: P8_11 = 0x0D 
except: pass

# pruio_pins.bi: 37
try: P8_12 = 0x0C 
except: pass

# pruio_pins.bi: 39
try: P8_13 = 0x09 
except: pass

# pruio_pins.bi: 41
try: P8_14 = 0x0A 
except: pass

# pruio_pins.bi: 43
try: P8_15 = 0x0F 
except: pass

# pruio_pins.bi: 45
try: P8_16 = 0x0E 
except: pass

# pruio_pins.bi: 47
try: P8_17 = 0x0B 
except: pass

# pruio_pins.bi: 49
try: P8_18 = 0x23 
except: pass

# pruio_pins.bi: 51
try: P8_19 = 0x08 
except: pass

# pruio_pins.bi: 53
try: P8_20 = 0x21 
except: pass

# pruio_pins.bi: 55
try: P8_21 = 0x20 
except: pass

# pruio_pins.bi: 57
try: P8_22 = 0x05 
except: pass

# pruio_pins.bi: 59
try: P8_23 = 0x04 
except: pass

# pruio_pins.bi: 61
try: P8_24 = 0x01 
except: pass

# pruio_pins.bi: 63
try: P8_25 = 0x00 
except: pass

# pruio_pins.bi: 65
try: P8_26 = 0x1F 
except: pass

# pruio_pins.bi: 67
try: P8_27 = 0x38 
except: pass

# pruio_pins.bi: 69
try: P8_28 = 0x3A 
except: pass

# pruio_pins.bi: 71
try: P8_29 = 0x39 
except: pass

# pruio_pins.bi: 73
try: P8_30 = 0x3B 
except: pass

# pruio_pins.bi: 75
try: P8_31 = 0x36 
except: pass

# pruio_pins.bi: 77
try: P8_32 = 0x37 
except: pass

# pruio_pins.bi: 79
try: P8_33 = 0x35 
except: pass

# pruio_pins.bi: 81
try: P8_34 = 0x33 
except: pass

# pruio_pins.bi: 83
try: P8_35 = 0x34 
except: pass

# pruio_pins.bi: 85
try: P8_36 = 0x32 
except: pass

# pruio_pins.bi: 87
try: P8_37 = 0x30 
except: pass

# pruio_pins.bi: 89
try: P8_38 = 0x31 
except: pass

# pruio_pins.bi: 91
try: P8_39 = 0x2E 
except: pass

# pruio_pins.bi: 93
try: P8_40 = 0x2F 
except: pass

# pruio_pins.bi: 95
try: P8_41 = 0x2C 
except: pass

# pruio_pins.bi: 97
try: P8_42 = 0x2D 
except: pass

# pruio_pins.bi: 99
try: P8_43 = 0x2A 
except: pass

# pruio_pins.bi: 101
try: P8_44 = 0x2B 
except: pass

# pruio_pins.bi: 103
try: P8_45 = 0x28 
except: pass

# pruio_pins.bi: 105
try: P8_46 = 0x29 
except: pass

# pruio_pins.bi: 108
try: P9_11 = 0x1C 
except: pass

# pruio_pins.bi: 110
try: P9_12 = 0x1E 
except: pass

# pruio_pins.bi: 112
try: P9_13 = 0x1D 
except: pass

# pruio_pins.bi: 114
try: P9_14 = 0x12 
except: pass

# pruio_pins.bi: 116
try: P9_15 = 0x10 
except: pass

# pruio_pins.bi: 118
try: P9_16 = 0x13 
except: pass

# pruio_pins.bi: 120
try: P9_17 = 0x57 
except: pass

# pruio_pins.bi: 122
try: P9_18 = 0x56 
except: pass

# pruio_pins.bi: 124
try: P9_19 = 0x5F 
except: pass

# pruio_pins.bi: 126
try: P9_20 = 0x5E 
except: pass

# pruio_pins.bi: 128
try: P9_21 = 0x55 
except: pass

# pruio_pins.bi: 130
try: P9_22 = 0x54 
except: pass

# pruio_pins.bi: 132
try: P9_23 = 0x11 
except: pass

# pruio_pins.bi: 134
try: P9_24 = 0x61 
except: pass

# pruio_pins.bi: 136
try: P9_25 = 0x6B 
except: pass

# pruio_pins.bi: 138
try: P9_26 = 0x60 
except: pass

# pruio_pins.bi: 140
try: P9_27 = 0x69 
except: pass

# pruio_pins.bi: 142
try: P9_28 = 0x67 
except: pass

# pruio_pins.bi: 144
try: P9_29 = 0x65 
except: pass

# pruio_pins.bi: 146
try: P9_30 = 0x66 
except: pass

# pruio_pins.bi: 148
try: P9_31 = 0x64 
except: pass

# pruio_pins.bi: 150
try: P9_41 = 0x6D 
except: pass

# pruio_pins.bi: 152
try: P9_42 = 0x59 
except: pass

# pruio_pins.bi: 155
try: JT_04 = 0x5C 
except: pass

# pruio_pins.bi: 157
try: JT_05 = 0x5D 
except: pass

# pruio_pins.bi: 160
try: AIN0 = 1
except: pass

# pruio_pins.bi: 162
try: AIN1 = 2
except: pass

# pruio_pins.bi: 164
try: AIN2 = 3
except: pass

# pruio_pins.bi: 166
try: AIN3 = 4
except: pass

# pruio_pins.bi: 168
try: AIN4 = 5
except: pass

# pruio_pins.bi: 170
try: AIN5 = 6
except: pass

# pruio_pins.bi: 172
try: AIN6 = 7
except: pass

# pruio_pins.bi: 174
try: AIN7 = 8
except: pass

# pruio_pins.bi: 176
try: P9_39 = AIN0
except: pass

# pruio_pins.bi: 178
try: P9_40 = AIN1
except: pass

# pruio_pins.bi: 180
try: P9_37 = AIN2
except: pass

# pruio_pins.bi: 182
try: P9_38 = AIN3
except: pass

# pruio_pins.bi: 184
try: P9_33 = AIN4
except: pass

# pruio_pins.bi: 186
try: P9_36 = AIN5
except: pass

# pruio_pins.bi: 188
try: P9_35 = AIN6
except: pass

# pruio_pins.bi: 236
P8_Pins = [ 
  P8_03 
, P8_04 
, P8_05 
, P8_06 
, P8_07 
, P8_08 
, P8_09 
, P8_10 
, P8_11 
, P8_12 
, P8_13 
, P8_14 
, P8_15 
, P8_16 
, P8_17 
, P8_18 
, P8_19 
, P8_20 
, P8_21 
, P8_22 
, P8_23 
, P8_24 
, P8_25 
, P8_26 
, P8_27 
, P8_28 
, P8_29 
, P8_30 
, P8_31 
, P8_32 
, P8_33 
, P8_34 
, P8_35 
, P8_36 
, P8_37 
, P8_38 
, P8_39 
, P8_40 
, P8_41 
, P8_42 
, P8_43 
, P8_44 
, P8_45 
, P8_46 
  ]

# pruio_pins.bi: 263
P9_Pins = [ 
  P9_11 
, P9_12 
, P9_13 
, P9_14 
, P9_15 
, P9_16 
, P9_17 
, P9_18 
, P9_19 
, P9_20 
, P9_21 
, P9_22 
, P9_23 
, P9_24 
, P9_25 
, P9_26 
, P9_27 
, P9_28 
, P9_29 
, P9_30 
, P9_31 
, P9_41 
, P9_42 
  ]

# pruio_pins.bi: 277
EMMC2_Pins = [ 
  P8_03 
, P8_04 
, P8_05 
, P8_06 
, P8_20 
, P8_21 
, P8_22 
, P8_23 
, P8_24 
, P8_25 
  ]

# pruio_pins.bi: 301
HDMI_Pins = [ 
  P8_27 
, P8_28 
, P8_29 
, P8_30 
, P8_31 
, P8_32 
, P8_33 
, P8_34 
, P8_35 
, P8_36 
, P8_37 
, P8_38 
, P8_39 
, P8_40 
, P8_41 
, P8_42 
, P8_43 
, P8_44 
, P8_45 
, P8_46 
  ]

# pruio_pins.bi: 307
I2C1_Pins = [ 
  P9_17 
, P9_18 
  ]

# pruio_pins.bi: 313
I2C2_Pins = [ 
  P9_19 
, P9_20 
  ]

# pruio_pins.bi: 321
MCASP0_Pins = [ 
  P9_25 
, P9_28 
, P9_29 
, P9_31 
  ]


# pruio.hp: 97
try: PRUIO_IRPT = 25
except: pass

# pruio.hp: 98
try: IRPT = PRUIO_IRPT + 16
except: pass

# pruio.hp: 99
try: CTBIR = 0x22020
except: pass

# pruio.hp: 100
try: CONST_PRUCFG = C4
except: pass

# pruio.hp: 101
try: DRam = C24
except: pass

# pruio.hp: 103
try: PRUIO_AZ_BALL = 109
except: pass

# pruio.hp: 104
try: PRUIO_AZ_GPIO = 3
except: pass

# pruio.hp: 105
try: PRUIO_AZ_PWMSS = 2
except: pass

# pruio.hp: 106
try: PRUIO_AZ_TIMER = 3
except: pass

# pruio.hp: 108
try: PRUIO_COM_POKE = 10
except: pass

# pruio.hp: 109
try: PRUIO_COM_PEEK = 9
except: pass

# pruio.hp: 110
try: PRUIO_COM_GPIO_CONF = 20
except: pass

# pruio.hp: 111
try: PRUIO_COM_GPIO_OUT = 19
except: pass

# pruio.hp: 112
try: PRUIO_COM_PWM = 30
except: pass

# pruio.hp: 113
try: PRUIO_COM_CAP_PWM = 29
except: pass

# pruio.hp: 114
try: PRUIO_COM_CAP = 28
except: pass

# pruio.hp: 115
try: PRUIO_COM_QEP = 27
except: pass

# pruio.hp: 116
try: PRUIO_COM_TIM_PWM = 40
except: pass

# pruio.hp: 117
try: PRUIO_COM_TIM_CAP = 38
except: pass

# pruio.hp: 118
try: PRUIO_COM_ADC = 50
except: pass

# pruio.hp: 120
try: PRUIO_DAT_GPIO = 64
except: pass

# pruio.hp: 121
try: PRUIO_DAT_PWM = 128
except: pass

# pruio.hp: 122
try: PRUIO_DAT_TIMER = 224
except: pass

# pruio.hp: 123
try: PRUIO_DAT_ADC = 288
except: pass

# pruio.hp: 124
try: PRUIO_DAT_ALL = 512
except: pass

# pruio.hp: 126
try: PRUIO_MSG_INIT_RUN = 4294967295
except: pass

# pruio.hp: 127
try: PRUIO_MSG_CONF_RUN = 4294967294
except: pass

# pruio.hp: 128
try: PRUIO_MSG_INIT_OK = 4294967293
except: pass

# pruio.hp: 129
try: PRUIO_MSG_CONF_OK = 4294967292
except: pass

# pruio.hp: 130
try: PRUIO_MSG_ADC_ERRR = 4294967291
except: pass

# pruio.hp: 131
try: PRUIO_MSG_MM_WAIT = 4294967290
except: pass

# pruio.hp: 132
try: PRUIO_MSG_MM_TRG1 = 4294967289
except: pass

# pruio.hp: 133
try: PRUIO_MSG_MM_TRG2 = 4294967288
except: pass

# pruio.hp: 134
try: PRUIO_MSG_MM_TRG3 = 4294967287
except: pass

# pruio.hp: 135
try: PRUIO_MSG_MM_TRG4 = 4294967286
except: pass

# pruio.hp: 136
try: PRUIO_MSG_IO_OK = 4294967285
except: pass


# pruio_globals.bi: 14
try: PRUIO_DEF_AVRAGE = 4
except: pass

# pruio_globals.bi: 16
try: PRUIO_DEF_ODELAY = 183
except: pass

# pruio_globals.bi: 18
try: PRUIO_DEF_SDELAY = 0
except: pass

# pruio_globals.bi: 20
try: PRUIO_DEF_SAMPLS = 1
except: pass

# pruio_globals.bi: 22
try: PRUIO_DEF_STPMSK = 0b111111110
except: pass

# pruio_globals.bi: 24
try: PRUIO_DEF_TIMERV = 0
except: pass

# pruio_globals.bi: 26
try: PRUIO_DEF_LSLMOD = 4
except: pass

# pruio_globals.bi: 28
try: PRUIO_DEF_CLKDIV = 0
except: pass

# pruio_globals.bi: 35
Int8 = c_byte

# pruio_globals.bi: 36
Int16 = c_short

# pruio_globals.bi: 37
Int32 = c_long

# pruio_globals.bi: 38
UInt8 = c_ubyte

# pruio_globals.bi: 39
UInt16 = c_ushort

# pruio_globals.bi: 40
UInt32 = c_ulong

# pruio_globals.bi: 41
Float_t = c_float

# pruio_globals.bi: 43
class PruIo(Structure):
  pass
Pruio_ = PruIo

# pruio_globals.bi: 44
class AdcUdt(Structure):
  pass
AdcUdt_ = AdcUdt

# pruio_globals.bi: 45
class GpioUdt(Structure):
  pass
GpioUdt_ = GpioUdt

# pruio_globals.bi: 46
class PwmssUdt(Structure):
  pass
PwmssUdt_ = PwmssUdt

# pruio_globals.bi: 47
class PwmMod(Structure):
  pass
PwmMod_ = PwmMod

# pruio_globals.bi: 48
class CapMod(Structure):
  pass
CapMod_ = CapMod

# pruio_globals.bi: 49
class QepMod(Structure):
  pass
QepMod_ = QepMod

# pruio_globals.bi: 50
class TimerUdt(Structure):
  pass
TimerUdt_ = TimerUdt

# pruio_globals.bi: 64
try: PRUIO_PULL_DOWN = 0b000000 
except: pass
try: PRUIO_NO_PULL = 0b001000 
except: pass
try: PRUIO_PULL_UP = 0b010000 
except: pass
try: PRUIO_RX_ACTIV = 0b100000 
except: pass
try: PRUIO_GPIO_OUT0 = 7 + PRUIO_NO_PULL                    
except: pass
try: PRUIO_GPIO_OUT1 = 7 + PRUIO_NO_PULL + 128              
except: pass
try: PRUIO_GPIO_IN = 7 + PRUIO_NO_PULL + PRUIO_RX_ACTIV   
except: pass
try: PRUIO_GPIO_IN_0 = 7 + PRUIO_PULL_DOWN + PRUIO_RX_ACTIV 
except: pass
try: PRUIO_GPIO_IN_1 = 7 + PRUIO_PULL_UP + PRUIO_RX_ACTIV   
except: pass
try: PRUIO_PIN_RESET = 0xFF
except: pass


# pruio_adc.bi: 29

class AdcSteps(Structure):
  pass 
AdcSteps._fields_ = [
  ('Confg', UInt32),
  ('Delay', UInt32),
]

# pruio_adc.bi: 75

class AdcSet(Structure):
  pass 
AdcSet._fields_ = [
  ('DeAd', UInt32),
  ('ClAd', UInt32),
  ('ClVa', UInt32),
  ('REVISION', UInt32),
  ('SYSCONFIG', UInt32),
  ('IRQSTATUS_RAW', UInt32),
  ('IRQSTATUS', UInt32),
  ('IRQENABLE_SET', UInt32),
  ('IRQENABLE_CLR', UInt32),
  ('IRQWAKEUP', UInt32),
  ('DMAENABLE_SET', UInt32),
  ('DMAENABLE_CLR', UInt32),
  ('CTRL', UInt32),
  ('ADCSTAT', UInt32),
  ('ADCRANGE', UInt32),
  ('ADC_CLKDIV', UInt32),
  ('ADC_MISC', UInt32),
  ('STEPENABLE', UInt32),
  ('IDLECONFIG', UInt32),
  ('St_p', AdcSteps * (16 + 1)),
  ('FIFO0COUNT', UInt32),
  ('FIFO0THRESHOLD', UInt32),
  ('DMA0REQ', UInt32),
  ('FIFO1COUNT', UInt32),
  ('FIFO1THRESHOLD', UInt32),
  ('DMA1REQ', UInt32),
]

# pruio_adc.bi: 139
AdcUdt._fields_ = [
  ('Top', POINTER(Pruio_)),
  ('Init', POINTER(AdcSet)),
  ('Conf', POINTER(AdcSet)),
  ('Samples', UInt32),
  ('TimerVal', UInt32),
  ('InitParA', UInt32),
  ('LslMode', UInt16),
  ('ChAz', UInt16),
  ('Value', POINTER(UInt16)),
  ('E0', c_char_p),
  ('E1', c_char_p),
  ('E2', c_char_p),
  ('E3', c_char_p),
  ('E4', c_char_p),
  ('E5', c_char_p),
]


# pruio_gpio.bi: 57

class GpioSet(Structure):
  pass 
GpioSet._fields_ = [
  ('DeAd', UInt32),
  ('ClAd', UInt32),
  ('ClVa', UInt32),
  ('REVISION', UInt32),
  ('SYSCONFIG', UInt32),
  ('EOI', UInt32),
  ('IRQSTATUS_RAW_0', UInt32),
  ('IRQSTATUS_RAW_1', UInt32),
  ('IRQSTATUS_0', UInt32),
  ('IRQSTATUS_1', UInt32),
  ('IRQSTATUS_SET_0', UInt32),
  ('IRQSTATUS_SET_1', UInt32),
  ('IRQSTATUS_CLR_0', UInt32),
  ('IRQSTATUS_CLR_1', UInt32),
  ('IRQWAKEN_0', UInt32),
  ('IRQWAKEN_1', UInt32),
  ('SYSSTATUS', UInt32),
  ('CTRL', UInt32),
  ('OE', UInt32),
  ('DATAIN', UInt32),
  ('DATAOUT', UInt32),
  ('LEVELDETECT0', UInt32),
  ('LEVELDETECT1', UInt32),
  ('RISINGDETECT', UInt32),
  ('FALLINGDETECT', UInt32),
  ('DEBOUNCENABLE', UInt32),
  ('DEBOUNCINGTIME', UInt32),
  ('CLEARDATAOUT', UInt32),
  ('SETDATAOUT', UInt32),
]

# pruio_gpio.bi: 75

class GpioArr(Structure):
  pass 
GpioArr._fields_ = [
  ('DeAd', UInt32),
  ('DATAIN', UInt32),
  ('DATAOUT', UInt32),
  ('Mix', UInt32),
]

# pruio_gpio.bi: 111
GpioUdt._fields_ = [
  ('Top', POINTER(Pruio_)),
  ('Init', POINTER(GpioSet) * (PRUIO_AZ_GPIO + 1)),
  ('Conf', POINTER(GpioSet) * (PRUIO_AZ_GPIO + 1)),
  ('Raw', POINTER(GpioArr) * (PRUIO_AZ_GPIO + 1)),
  ('InitParA', UInt32),
  ('E0', c_char_p),
  ('E1', c_char_p),
]


# pruio_pwmss.bi: 134

class PwmssSet(Structure):
  pass 
PwmssSet._fields_ = [
  ('DeAd', UInt32),
  ('ClAd', UInt32),
  ('ClVa', UInt32),
  ('IDVER', UInt32),
  ('SYSCONFIG', UInt32),
  ('CLKCONFIG', UInt32),
  ('CLKSTATUS', UInt32),
  ('TSCTR', UInt32),
  ('CTRPHS', UInt32),
  ('CAP1', UInt32),
  ('CAP2', UInt32),
  ('CAP3', UInt32),
  ('CAP4', UInt32),
  ('ECCTL1', UInt16),
  ('ECCTL2', UInt16),
  ('ECEINT', UInt16),
  ('ECFLG', UInt16),
  ('ECCLR', UInt16),
  ('ECFRC', UInt16),
  ('CAP_REV', UInt32),
  ('QPOSCNT', UInt32),
  ('QPOSINIT', UInt32),
  ('QPOSMAX', UInt32),
  ('QPOSCMP', UInt32),
  ('QPOSILAT', UInt32),
  ('QPOSSLAT', UInt32),
  ('QPOSLAT', UInt32),
  ('QUTMR', UInt32),
  ('QUPRD', UInt32),
  ('QWDTMR', UInt16),
  ('QWDPRD', UInt16),
  ('QDECCTL', UInt16),
  ('QEPCTL', UInt16),
  ('QCAPCTL', UInt16),
  ('QPOSCTL', UInt16),
  ('QEINT', UInt16),
  ('QFLG', UInt16),
  ('QCLR', UInt16),
  ('QFRC', UInt16),
  ('QEPSTS', UInt16),
  ('QCTMR', UInt16),
  ('QCPRD', UInt16),
  ('QCTMRLAT', UInt16),
  ('QCPRDLAT', UInt16),
  ('empty', UInt16),
  ('QEP_REV', UInt32),
  ('TBCTL', UInt16),
  ('TBSTS', UInt16),
  ('TBPHSHR', UInt16),
  ('TBPHS', UInt16),
  ('TBCNT', UInt16),
  ('TBPRD', UInt16),
  ('CMPCTL', UInt16),
  ('CMPAHR', UInt16),
  ('CMPA', UInt16),
  ('CMPB', UInt16),
  ('AQCTLA', UInt16),
  ('AQCTLB', UInt16),
  ('AQSFRC', UInt16),
  ('AQCSFRC', UInt16),
  ('DBCTL', UInt16),
  ('DBRED', UInt16),
  ('DBFED', UInt16),
  ('TZSEL', UInt16),
  ('TZCTL', UInt16),
  ('TZEINT', UInt16),
  ('TZFLG', UInt16),
  ('TZCLR', UInt16),
  ('TZFRC', UInt16),
  ('ETSEL', UInt16),
  ('ETPS', UInt16),
  ('ETFLG', UInt16),
  ('ETCLR', UInt16),
  ('ETFRC', UInt16),
  ('PCCTL', UInt16),
  ('HRCTL', UInt16),
]

# pruio_pwmss.bi: 157

class PwmssArr(Structure):
  pass 
PwmssArr._fields_ = [
  ('DeAd', UInt32),
  ('CMax', UInt32),
  ('C1', UInt32),
  ('C2', UInt32),
  ('QPos', UInt32),
  ('NPos', UInt32),
  ('OPos', UInt32),
  ('PLat', UInt32),
]

# pruio_pwmss.bi: 224
PwmssUdt._fields_ = [
  ('Top', POINTER(Pruio_)),
  ('Init', POINTER(PwmssSet) * (PRUIO_AZ_PWMSS + 1)),
  ('Conf', POINTER(PwmssSet) * (PRUIO_AZ_PWMSS + 1)),
  ('Raw', POINTER(PwmssArr) * (PRUIO_AZ_PWMSS + 1)),
  ('InitParA', UInt32),
  ('PwmMode', UInt16),
  ('CapMode', UInt16),
  ('E0', c_char_p),
  ('E1', c_char_p),
  ('E2', c_char_p),
  ('E3', c_char_p),
  ('E4', c_char_p),
  ('E5', c_char_p),
  ('E6', c_char_p),
  ('E7', c_char_p),
  ('E8', c_char_p),
  ('E9', c_char_p),
]

# pruio_pwmss.bi: 272
PwmMod._fields_ = [
  ('Top', POINTER(Pruio_)),
  ('ForceUpDown', UInt16),
  ('Cntrl', UInt16 * (PRUIO_AZ_PWMSS + 1)),
  ('AqCtl', UInt16 * ((1 + 1) * (PRUIO_AZ_PWMSS + 1) * (2 + 1))),
]

# pruio_pwmss.bi: 299
CapMod._fields_ = [
  ('Top', POINTER(Pruio_)),
]

# pruio_pwmss.bi: 332
QepMod._fields_ = [
  ('Top', POINTER(Pruio_)),
  ('FVh', Float_t * (PRUIO_AZ_PWMSS + 1)),
  ('FVl', Float_t * (PRUIO_AZ_PWMSS + 1)),
  ('Prd', UInt32 * (PRUIO_AZ_PWMSS + 1)),
]


# pruio_timer.bi: 45

class TimerSet(Structure):
  pass 
TimerSet._fields_ = [
  ('DeAd', UInt32),
  ('ClAd', UInt32),
  ('ClVa', UInt32),
  ('TIDR', UInt32),
  ('TIOCP_CFG', UInt32),
  ('IRQ_EOI', UInt32),
  ('IRQSTATUS_RAW', UInt32),
  ('IRQSTATUS', UInt32),
  ('IRQENABLE_SET', UInt32),
  ('IRQENABLE_CLR', UInt32),
  ('IRQWAKEEN', UInt32),
  ('TCLR', UInt32),
  ('TCRR', UInt32),
  ('TLDR', UInt32),
  ('TTGR', UInt32),
  ('TWPS', UInt32),
  ('TMAR', UInt32),
  ('TCAR1', UInt32),
  ('TSICR', UInt32),
  ('TCAR2', UInt32),
]

# pruio_timer.bi: 61

class TimerArr(Structure):
  pass 
TimerArr._fields_ = [
  ('DeAd', UInt32),
  ('CMax', UInt32),
  ('TCAR1', UInt32),
  ('TCAR2', UInt32),
]

# pruio_timer.bi: 117
TimerUdt._fields_ = [
  ('Top', POINTER(Pruio_)),
  ('Init', POINTER(TimerSet) * (PRUIO_AZ_TIMER + 1)),
  ('Conf', POINTER(TimerSet) * (PRUIO_AZ_TIMER + 1)),
  ('Raw', POINTER(TimerArr) * (PRUIO_AZ_TIMER + 1)),
  ('InitParA', UInt32),
  ('PwmMode', UInt32),
  ('TimMode', UInt32),
  ('TimHigh', UInt32),
  ('Tim_Low', UInt32),
  ('CapMode', UInt32),
  ('E0', c_char_p),
  ('E1', c_char_p),
  ('E2', c_char_p),
]


# pruio.bi: 36
try: PRUIO_CHAN = CHANNEL5
except: pass

# pruio.bi: 38
try: PRUIO_MASK = PRU_EVTOUT5_HOSTEN_MASK
except: pass

# pruio.bi: 40
try: PRUIO_EMAP = PRU_EVTOUT5
except: pass

# pruio.bi: 42
try: PRUIO_EVNT = PRU_EVTOUT_5
except: pass

# pruio.bi: 86
try: PRUIO_ACT_PRU1 = 0b0000000000001 
except: pass
try: PRUIO_ACT_ADC = 0b0000000000010 
except: pass
try: PRUIO_ACT_GPIO0 = 0b0000000000100 
except: pass
try: PRUIO_ACT_GPIO1 = 0b0000000001000 
except: pass
try: PRUIO_ACT_GPIO2 = 0b0000000010000 
except: pass
try: PRUIO_ACT_GPIO3 = 0b0000000100000 
except: pass
try: PRUIO_ACT_PWM0 = 0b0000001000000 
except: pass
try: PRUIO_ACT_PWM1 = 0b0000010000000 
except: pass
try: PRUIO_ACT_PWM2 = 0b0000100000000 
except: pass
try: PRUIO_ACT_TIM4 = 0b0001000000000 
except: pass
try: PRUIO_ACT_TIM5 = 0b0010000000000 
except: pass
try: PRUIO_ACT_TIM6 = 0b0100000000000 
except: pass
try: PRUIO_ACT_TIM7 = 0b1000000000000 
except: pass
try: PRUIO_DEF_ACTIVE = 0b1111111111111 
except: pass

# pruio.bi: 102

class BallSet(Structure):
  pass 
BallSet._fields_ = [
  ('DeAd', UInt32),
  ('Value', UInt8 * (PRUIO_AZ_BALL + 1)),
]

# pruio.bi: 221
PruIo._fields_ = [
  ('Errr', c_char_p),
  ('Adc', POINTER(AdcUdt)),
  ('Gpio', POINTER(GpioUdt)),
  ('PwmSS', POINTER(PwmssUdt)),
  ('TimSS', POINTER(TimerUdt)),
  ('Pwm', POINTER(PwmMod)),
  ('Cap', POINTER(CapMod)),
  ('Qep', POINTER(QepMod)),
  ('Tim', POINTER(TimerUdt)),
  ('DRam', POINTER(UInt32)),
  ('Init', POINTER(BallSet)),
  ('Conf', POINTER(BallSet)),
  ('ERam', c_void_p),
  ('DInit', c_void_p),
  ('DConf', c_void_p),
  ('MOffs', c_void_p),
  ('BallInit', POINTER(UInt8)),
  ('BallConf', POINTER(UInt8)),
  ('EAddr', UInt32),
  ('ESize', UInt32),
  ('DSize', UInt32),
  ('PruNo', UInt32),
  ('PruIRam', UInt32),
  ('PruDRam', UInt32),
  ('ParOffs', Int16),
  ('DevAct', Int16),
  ('BallGpio', UInt8 * (PRUIO_AZ_BALL + 1)),
  ('IntcInit', tpruss_intc_initdata),
  ('MuxAcc', c_void_p * 3),
]


# pruio_c_wrapper.bas: 28
if hasattr(_libs['pruio'], 'pruio_new'):
  pruio_new = _libs['pruio'].pruio_new
  pruio_new.argtypes = [UInt16, UInt8, UInt32, UInt8]
  pruio_new.restype = POINTER(PruIo)

# pruio_c_wrapper.bas: 35
if hasattr(_libs['pruio'], 'pruio_destroy'):
  pruio_destroy = _libs['pruio'].pruio_destroy
  pruio_destroy.argtypes = [POINTER(PruIo)]
  pruio_destroy.restype = None

# pruio_c_wrapper.bas: 46
if hasattr(_libs['pruio'], 'pruio_config'):
  pruio_config = _libs['pruio'].pruio_config
  pruio_config.argtypes = [POINTER(PruIo), UInt32, UInt32, UInt32, UInt16]
  if sizeof(c_int) == sizeof(c_void_p):
      pruio_config.restype = ReturnString
  else:
      pruio_config.restype = String
      pruio_config.errcheck = ReturnString

# pruio_c_wrapper.bas: 55
if hasattr(_libs['pruio'], 'pruio_Pin'):
  pruio_Pin = _libs['pruio'].pruio_Pin
  pruio_Pin.argtypes = [POINTER(PruIo), UInt8, UInt8]
  if sizeof(c_int) == sizeof(c_void_p):
      pruio_Pin.restype = ReturnString
  else:
      pruio_Pin.restype = String
      pruio_Pin.errcheck = ReturnString

# pruio_c_wrapper.bas: 66
if hasattr(_libs['pruio'], 'pruio_mm_start'):
  pruio_mm_start = _libs['pruio'].pruio_mm_start
  pruio_mm_start.argtypes = [POINTER(PruIo), UInt32, UInt32, UInt32, UInt32]
  if sizeof(c_int) == sizeof(c_void_p):
      pruio_mm_start.restype = ReturnString
  else:
      pruio_mm_start.restype = String
      pruio_mm_start.errcheck = ReturnString

# pruio_c_wrapper.bas: 73
if hasattr(_libs['pruio'], 'pruio_rb_start'):
  pruio_rb_start = _libs['pruio'].pruio_rb_start
  pruio_rb_start.argtypes = [POINTER(PruIo)]
  if sizeof(c_int) == sizeof(c_void_p):
      pruio_rb_start.restype = ReturnString
  else:
      pruio_rb_start.restype = String
      pruio_rb_start.errcheck = ReturnString

# pruio_c_wrapper.bas: 86
if hasattr(_libs['pruio'], 'pruio_adc_setStep'):
  pruio_adc_setStep = _libs['pruio'].pruio_adc_setStep
  pruio_adc_setStep.argtypes = [POINTER(PruIo), UInt8, UInt8, UInt8, UInt8, UInt32]
  if sizeof(c_int) == sizeof(c_void_p):
      pruio_adc_setStep.restype = ReturnString
  else:
      pruio_adc_setStep.restype = String
      pruio_adc_setStep.errcheck = ReturnString

# pruio_c_wrapper.bas: 96
if hasattr(_libs['pruio'], 'pruio_adc_mm_trg_pin'):
  pruio_adc_mm_trg_pin = _libs['pruio'].pruio_adc_mm_trg_pin
  pruio_adc_mm_trg_pin.argtypes = [POINTER(PruIo), UInt8, UInt8, UInt16]
  pruio_adc_mm_trg_pin.restype = UInt32

# pruio_c_wrapper.bas: 107
if hasattr(_libs['pruio'], 'pruio_adc_mm_trg_ain'):
  pruio_adc_mm_trg_ain = _libs['pruio'].pruio_adc_mm_trg_ain
  pruio_adc_mm_trg_ain.argtypes = [POINTER(PruIo), UInt8, Int32, UInt8, UInt16]
  pruio_adc_mm_trg_ain.restype = UInt32

# pruio_c_wrapper.bas: 118
if hasattr(_libs['pruio'], 'pruio_adc_mm_trg_pre'):
  pruio_adc_mm_trg_pre = _libs['pruio'].pruio_adc_mm_trg_pre
  pruio_adc_mm_trg_pre.argtypes = [POINTER(PruIo), UInt8, Int32, UInt16, UInt8]
  pruio_adc_mm_trg_pre.restype = UInt32

# pruio_c_wrapper.bas: 128
if hasattr(_libs['pruio'], 'pruio_gpio_config'):
  pruio_gpio_config = _libs['pruio'].pruio_gpio_config
  pruio_gpio_config.argtypes = [POINTER(PruIo), UInt8, UInt8]
  if sizeof(c_int) == sizeof(c_void_p):
      pruio_gpio_config.restype = ReturnString
  else:
      pruio_gpio_config.restype = String
      pruio_gpio_config.errcheck = ReturnString

# pruio_c_wrapper.bas: 137
if hasattr(_libs['pruio'], 'pruio_gpio_setValue'):
  pruio_gpio_setValue = _libs['pruio'].pruio_gpio_setValue
  pruio_gpio_setValue.argtypes = [POINTER(PruIo), UInt8, UInt8]
  if sizeof(c_int) == sizeof(c_void_p):
      pruio_gpio_setValue.restype = ReturnString
  else:
      pruio_gpio_setValue.restype = String
      pruio_gpio_setValue.errcheck = ReturnString

# pruio_c_wrapper.bas: 145
if hasattr(_libs['pruio'], 'pruio_gpio_Value'):
  pruio_gpio_Value = _libs['pruio'].pruio_gpio_Value
  pruio_gpio_Value.argtypes = [POINTER(PruIo), UInt8]
  pruio_gpio_Value.restype = UInt32

# pruio_c_wrapper.bas: 155
if hasattr(_libs['pruio'], 'pruio_cap_config'):
  pruio_cap_config = _libs['pruio'].pruio_cap_config
  pruio_cap_config.argtypes = [POINTER(PruIo), UInt8, Float_t]
  if sizeof(c_int) == sizeof(c_void_p):
      pruio_cap_config.restype = ReturnString
  else:
      pruio_cap_config.restype = String
      pruio_cap_config.errcheck = ReturnString

# pruio_c_wrapper.bas: 165
if hasattr(_libs['pruio'], 'pruio_cap_Value'):
  pruio_cap_Value = _libs['pruio'].pruio_cap_Value
  pruio_cap_Value.argtypes = [POINTER(PruIo), UInt8, POINTER(Float_t), POINTER(Float_t)]
  if sizeof(c_int) == sizeof(c_void_p):
      pruio_cap_Value.restype = ReturnString
  else:
      pruio_cap_Value.restype = String
      pruio_cap_Value.errcheck = ReturnString

# pruio_c_wrapper.bas: 178
if hasattr(_libs['pruio'], 'pruio_qep_config'):
  pruio_qep_config = _libs['pruio'].pruio_qep_config
  pruio_qep_config.argtypes = [POINTER(PruIo), UInt8, UInt32, Float_t, Float_t, UInt8]
  if sizeof(c_int) == sizeof(c_void_p):
      pruio_qep_config.restype = ReturnString
  else:
      pruio_qep_config.restype = String
      pruio_qep_config.errcheck = ReturnString

# pruio_c_wrapper.bas: 188
if hasattr(_libs['pruio'], 'pruio_qep_Value'):
  pruio_qep_Value = _libs['pruio'].pruio_qep_Value
  pruio_qep_Value.argtypes = [POINTER(PruIo), UInt8, POINTER(UInt32), POINTER(Float_t)]
  if sizeof(c_int) == sizeof(c_void_p):
      pruio_qep_Value.restype = ReturnString
  else:
      pruio_qep_Value.restype = String
      pruio_qep_Value.errcheck = ReturnString

# pruio_c_wrapper.bas: 199
if hasattr(_libs['pruio'], 'pruio_pwm_Value'):
  pruio_pwm_Value = _libs['pruio'].pruio_pwm_Value
  pruio_pwm_Value.argtypes = [POINTER(PruIo), UInt8, POINTER(Float_t), POINTER(Float_t)]
  if sizeof(c_int) == sizeof(c_void_p):
      pruio_pwm_Value.restype = ReturnString
  else:
      pruio_pwm_Value.restype = String
      pruio_pwm_Value.errcheck = ReturnString

# pruio_c_wrapper.bas: 209
if hasattr(_libs['pruio'], 'pruio_pwm_setValue'):
  pruio_pwm_setValue = _libs['pruio'].pruio_pwm_setValue
  pruio_pwm_setValue.argtypes = [POINTER(PruIo), UInt8, Float_t, Float_t]
  if sizeof(c_int) == sizeof(c_void_p):
      pruio_pwm_setValue.restype = ReturnString
  else:
      pruio_pwm_setValue.restype = String
      pruio_pwm_setValue.errcheck = ReturnString

# pruio_c_wrapper.bas: 221
if hasattr(_libs['pruio'], 'pruio_tim_Value'):
  pruio_tim_Value = _libs['pruio'].pruio_tim_Value
  pruio_tim_Value.argtypes = [POINTER(PruIo), UInt8, POINTER(Float_t), POINTER(Float_t), POINTER(UInt16)]
  if sizeof(c_int) == sizeof(c_void_p):
      pruio_tim_Value.restype = ReturnString
  else:
      pruio_tim_Value.restype = String
      pruio_tim_Value.errcheck = ReturnString

# pruio_c_wrapper.bas: 232
if hasattr(_libs['pruio'], 'pruio_tim_setValue'):
  pruio_tim_setValue = _libs['pruio'].pruio_tim_setValue
  pruio_tim_setValue.argtypes = [POINTER(PruIo), UInt8, Float_t, Float_t, UInt16]
  if sizeof(c_int) == sizeof(c_void_p):
      pruio_tim_setValue.restype = ReturnString
  else:
      pruio_tim_setValue.restype = String
      pruio_tim_setValue.errcheck = ReturnString
